spring.application.name=recipe-hub-backend

# ===============================
# DATABASE CONFIG (MySQL)
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/recipehub_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
	
# ===============================
# SERVER
# ===============================

server.port=8080


# ===============================
# CORS
# ===============================

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:3000}

